[package]
name = "uniswap_v3_math"
version = "0.4.1"
edition = "2021"
license = "MIT"
description = "Uniswap V3 math in Rust"
readme = "README.md"
homepage = "https://github.com/0xKitsune/uniswap_v3_math"
repository = "https://github.com/0xKitsune/uniswap_v3_math"
keywords = ["uniswapV3", "math"]
exclude = ["target/*", ".github/*", ".gitignore", "Uniswap/*"]

[dependencies]
# ethers = { version = "2.0.0", default-features = false, features = ["abigen"] }
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "fd8f065", features = [
    # "dyn-abi",
    # "json-abi",
    # "json",
    "sol-types",
    # "rlp",
    # "serde",
    "contract",
    # "consensus",
    # "eips",
    "network",
    # "genesis",
    "node-bindings",
    "providers",
    "rpc",
    # "json-rpc",
    "rpc-client",
    # "rpc-types",
    "rpc-types-eth",
    # "rpc-types-engine",
    # "rpc-types-trace",
    "signers",
    # "signer-aws",
    # "signer-gcp",
    "signer-ledger",
    "signer-trezor",
    "signer-wallet",
    "signer-mnemonic",
    "signer-yubihsm",
    # "transports",
    "transport-http",
    # "transport-ipc",
    # "transport-ws",
    # "pubsub",
] }

eyre = "0.6.8"
thiserror = "1.0.38"


# TODO: sol! macro somehow requires this to be present
alloy-sol-types = { version = "0.6.4", default-features = false, features = [
    "std",
] }

[patch.crates-io]
alloy-core = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
alloy-dyn-abi = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
alloy-json-abi = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
alloy-primitives = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
alloy-sol-types = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
