[package]
name = "uniswap_v3_math"
version = "0.4.1"
edition = "2021"
license = "MIT"
description = "Uniswap V3 math in Rust"
readme = "README.md"
homepage = "https://github.com/0xKitsune/uniswap_v3_math"
repository = "https://github.com/0xKitsune/uniswap_v3_math"
keywords = ["uniswapV3", "math"]
exclude = ["target/*", ".github/*", ".gitignore", "Uniswap/*"]

[dependencies]
# ethers = { version = "2.0.0", default-features = false, features = ["abigen"] }
# alloy-primitives = { git = "https://github.com/alloy-rs/alloy.git", rev = "f9c90dececc991486eb483f3f9398bb2714fb8a0" }
alloy-provider = { git = "https://github.com/alloy-rs/alloy.git", rev = "f9c90dececc991486eb483f3f9398bb2714fb8a0" }
alloy-contract = { git = "https://github.com/alloy-rs/alloy.git", rev = "f9c90dececc991486eb483f3f9398bb2714fb8a0" } 
alloy = { git = "https://github.com/alloy-rs/alloy.git", rev = "f9c90dececc991486eb483f3f9398bb2714fb8a0" } 

eyre = "0.6.8"
# ruint = "1.7.0"
thiserror = "1.0.38"
